/**
 * One-time passcodes for customer and provider login.
 *
 * Rules enforced here:
 *   - the code is generated by a CSPRNG and never stored, only its HMAC
 *   - it expires after OTP_TTL_SECONDS (5 minutes by default)
 *   - at most OTP_MAX_ATTEMPTS wrong guesses, then the code dies
 *   - a resend cooldown, plus per-phone and per-IP hourly limits
 *   - comparison is constant time
 *   - a code can be consumed exactly once
 *
 * The SMS text itself is not built here: the caller passes a renderer, so
 * every user-facing string stays in messages/*.json and this module stays
 * free of i18n coupling and easy to test.
 */
import "server-only";

import { hmacOtp, hashIp, randomNumericCode, safeEqual } from "../crypto";
import { prisma } from "../db";
import { env } from "../env";
import { loggerFor } from "../logger";
import { maskPhone } from "../phone";
import { consumeLimit, RATE_LIMITS } from "../rate-limit";
import { smsProvider } from "../sms";

import type { OtpPurpose } from "@prisma/client";

const log = loggerFor("auth/otp");

export type OtpRequestFailure =
  | "COOLDOWN"
  | "RATE_LIMITED_PHONE"
  | "RATE_LIMITED_IP"
  | "SEND_FAILED";

export type OtpRequestResult =
  | { ok: true; expiresAt: Date; resendAfterSeconds: number }
  | { ok: false; reason: OtpRequestFailure; retryAfterSeconds: number };

export type OtpVerifyFailure =
  | "NO_ACTIVE_CODE"
  | "EXPIRED"
  | "INVALID_CODE"
  | "TOO_MANY_ATTEMPTS"
  | "RATE_LIMITED";

export type OtpVerifyResult =
  | { ok: true }
  | { ok: false; reason: OtpVerifyFailure; attemptsLeft?: number };

export interface OtpContext {
  ip?: string | null;
}

/** Seconds until `date`, never negative. */
function secondsUntil(date: Date): number {
  return Math.max(0, Math.ceil((date.getTime() - Date.now()) / 1000));
}

/**
 * Issues a new code and sends it.
 *
 * Always invalidates any previous unconsumed code for the same phone and
 * purpose, so only the most recent code can ever be used.
 */
export async function requestOtp(
  phone: string,
  purpose: OtpPurpose,
  renderMessage: (code: string) => string,
  context: OtpContext = {},
): Promise<OtpRequestResult> {
  const phoneMasked = maskPhone(phone);

  // 1. Resend cooldown, based on the most recent code for this phone.
  const latest = await prisma.otpCode.findFirst({
    where: { phone, purpose },
    orderBy: { createdAt: "desc" },
    select: { createdAt: true },
  });

  if (latest) {
    const readyAt = new Date(
      latest.createdAt.getTime() + env.OTP_RESEND_COOLDOWN_SECONDS * 1000,
    );
    if (readyAt.getTime() > Date.now()) {
      return {
        ok: false,
        reason: "COOLDOWN",
        retryAfterSeconds: secondsUntil(readyAt),
      };
    }
  }

  // 2. Hourly limits. The phone limit protects the person; the IP limit
  //    protects us from SMS-pumping fraud once a paid gateway is connected.
  const perPhone = await consumeLimit("otpPerPhone", phone);
  if (!perPhone.allowed) {
    log.warn({ phoneMasked }, "otp request blocked: per-phone limit");
    return {
      ok: false,
      reason: "RATE_LIMITED_PHONE",
      retryAfterSeconds: secondsUntil(perPhone.resetAt),
    };
  }

  if (context.ip) {
    const perIp = await consumeLimit("otpPerIp", hashIp(context.ip) ?? "unknown");
    if (!perIp.allowed) {
      log.warn({ phoneMasked }, "otp request blocked: per-ip limit");
      return {
        ok: false,
        reason: "RATE_LIMITED_IP",
        retryAfterSeconds: secondsUntil(perIp.resetAt),
      };
    }
  }

  // 3. Issue the code.
  const code = randomNumericCode();
  const expiresAt = new Date(Date.now() + env.OTP_TTL_SECONDS * 1000);

  await prisma.$transaction([
    prisma.otpCode.updateMany({
      where: { phone, purpose, consumedAt: null },
      data: { consumedAt: new Date() },
    }),
    prisma.otpCode.create({
      data: {
        phone,
        purpose,
        codeHash: hmacOtp(code),
        expiresAt,
        ipHash: hashIp(context.ip),
      },
    }),
  ]);

  // 4. Deliver. Note that `code` is never passed to the logger.
  try {
    await smsProvider.send({ to: phone, body: renderMessage(code) });
  } catch (error) {
    log.error({ phoneMasked, err: error }, "otp sms send failed");
    return { ok: false, reason: "SEND_FAILED", retryAfterSeconds: 0 };
  }

  log.info({ phoneMasked, purpose }, "otp issued");

  return {
    ok: true,
    expiresAt,
    resendAfterSeconds: env.OTP_RESEND_COOLDOWN_SECONDS,
  };
}

/**
 * Checks a submitted code and consumes it on success.
 *
 * On a wrong guess the attempt counter rises; once it reaches the limit the
 * code is invalidated immediately, so six digits cannot be walked through.
 */
export async function verifyOtp(
  phone: string,
  code: string,
  purpose: OtpPurpose,
  context: OtpContext = {},
): Promise<OtpVerifyResult> {
  void context;
  const phoneMasked = maskPhone(phone);

  const attemptLimit = await consumeLimit("otpVerifyPerPhone", phone);
  if (!attemptLimit.allowed) {
    log.warn({ phoneMasked }, "otp verify blocked: rate limit");
    return { ok: false, reason: "RATE_LIMITED" };
  }

  const record = await prisma.otpCode.findFirst({
    where: { phone, purpose, consumedAt: null },
    orderBy: { createdAt: "desc" },
  });

  if (!record) return { ok: false, reason: "NO_ACTIVE_CODE" };

  if (record.expiresAt.getTime() <= Date.now()) {
    await prisma.otpCode.update({
      where: { id: record.id },
      data: { consumedAt: new Date() },
    });
    return { ok: false, reason: "EXPIRED" };
  }

  if (record.attempts >= env.OTP_MAX_ATTEMPTS) {
    await prisma.otpCode.update({
      where: { id: record.id },
      data: { consumedAt: new Date() },
    });
    return { ok: false, reason: "TOO_MANY_ATTEMPTS" };
  }

  if (!safeEqual(record.codeHash, hmacOtp(code))) {
    const attempts = record.attempts + 1;
    const exhausted = attempts >= env.OTP_MAX_ATTEMPTS;

    await prisma.otpCode.update({
      where: { id: record.id },
      data: { attempts, consumedAt: exhausted ? new Date() : null },
    });

    log.warn({ phoneMasked, attempts }, "otp verify failed");

    return exhausted
      ? { ok: false, reason: "TOO_MANY_ATTEMPTS", attemptsLeft: 0 }
      : {
          ok: false,
          reason: "INVALID_CODE",
          attemptsLeft: env.OTP_MAX_ATTEMPTS - attempts,
        };
  }

  // Consume atomically: the `consumedAt: null` guard means two parallel
  // submissions of the same correct code cannot both win.
  const consumed = await prisma.otpCode.updateMany({
    where: { id: record.id, consumedAt: null },
    data: { consumedAt: new Date() },
  });

  if (consumed.count === 0) return { ok: false, reason: "NO_ACTIVE_CODE" };

  log.info({ phoneMasked, purpose }, "otp verified");
  return { ok: true };
}

/** Maintenance: drop codes that are well past their usefulness. */
export async function pruneExpiredOtpCodes(olderThanHours = 24): Promise<number> {
  const cutoff = new Date(Date.now() - olderThanHours * 60 * 60 * 1000);
  const result = await prisma.otpCode.deleteMany({
    where: { createdAt: { lt: cutoff } },
  });
  return result.count;
}

export { RATE_LIMITS };
